// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Add Add
//
// swagger:model add
type Add string

// Validate validates this add
func (m Add) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this add based on context it is used
func (m Add) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
