// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Attribute Attribute
//
// swagger:model attribute
type Attribute string

// Validate validates this attribute
func (m Attribute) Validate(formats strfmt.Registry) error {
	return nil
}
