// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// ContributedBy ContributedBy
//
// swagger:model contributedBy
type ContributedBy string

// Validate validates this contributed by
func (m ContributedBy) Validate(formats strfmt.Registry) error {
	return nil
}
