// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Hop Hop
//
// swagger:model hop
type Hop struct {

	// add
	// Required: true
	Add *Add `json:"add"`

	// amount
	// Required: true
	Amount *BoilVolume `json:"amount"`

	// attribute
	// Required: true
	Attribute *Attribute `json:"attribute"`

	// name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this hop
func (m *Hop) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAttribute(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Hop) validateAdd(formats strfmt.Registry) error {

	if err := validate.Required("add", "body", m.Add); err != nil {
		return err
	}

	if err := validate.Required("add", "body", m.Add); err != nil {
		return err
	}

	if m.Add != nil {
		if err := m.Add.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("add")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("add")
			}
			return err
		}
	}

	return nil
}

func (m *Hop) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	if m.Amount != nil {
		if err := m.Amount.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("amount")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("amount")
			}
			return err
		}
	}

	return nil
}

func (m *Hop) validateAttribute(formats strfmt.Registry) error {

	if err := validate.Required("attribute", "body", m.Attribute); err != nil {
		return err
	}

	if err := validate.Required("attribute", "body", m.Attribute); err != nil {
		return err
	}

	if m.Attribute != nil {
		if err := m.Attribute.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("attribute")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("attribute")
			}
			return err
		}
	}

	return nil
}

func (m *Hop) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this hop based on the context it is used
func (m *Hop) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdd(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAttribute(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Hop) contextValidateAdd(ctx context.Context, formats strfmt.Registry) error {

	if m.Add != nil {
		if err := m.Add.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("add")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("add")
			}
			return err
		}
	}

	return nil
}

func (m *Hop) contextValidateAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.Amount != nil {
		if err := m.Amount.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("amount")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("amount")
			}
			return err
		}
	}

	return nil
}

func (m *Hop) contextValidateAttribute(ctx context.Context, formats strfmt.Registry) error {

	if m.Attribute != nil {
		if err := m.Attribute.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("attribute")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("attribute")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Hop) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Hop) UnmarshalBinary(b []byte) error {
	var res Hop
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
