// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Unit Unit
//
// swagger:model unit
type Unit string

// Validate validates this unit
func (m Unit) Validate(formats strfmt.Registry) error {
	return nil
}
