swagger: "2.0"
info:
  title: github.com/majodev/beer-punk-api
  version: 0.1.0
paths:
  /api/v1/admin/beers:
    post:
      security:
        - Management: []
      summary: Post Beer
      operationId: PostBeerRoute
      description: |-
        Admin
      tags:
        - admin
      parameters:
        - name: Payload
          in: body
          schema:
            $ref: ../definitions/admin.yml#/definitions/PostBeerPayload
      responses:
        "200":
          description: PostBeerResponse
          schema:
            $ref: ../definitions/beers.yml#/definitions/Beer
