// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBeers(t *testing.T) {
	t.Parallel()

	query := Beers()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBeersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Beers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBeersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Beers().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Beers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBeersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BeerSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Beers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBeersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BeerExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Beer exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BeerExists to return true, but got false.")
	}
}

func testBeersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	beerFound, err := FindBeer(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if beerFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBeersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Beers().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBeersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Beers().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBeersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	beerOne := &Beer{}
	beerTwo := &Beer{}
	if err = randomize.Struct(seed, beerOne, beerDBTypes, false, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}
	if err = randomize.Struct(seed, beerTwo, beerDBTypes, false, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = beerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = beerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Beers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBeersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	beerOne := &Beer{}
	beerTwo := &Beer{}
	if err = randomize.Struct(seed, beerOne, beerDBTypes, false, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}
	if err = randomize.Struct(seed, beerTwo, beerDBTypes, false, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = beerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = beerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Beers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testBeersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Beers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBeersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(beerColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Beers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBeersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBeersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BeerSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBeersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Beers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	beerDBTypes = map[string]string{`ID`: `integer`, `Name`: `text`, `Tagline`: `text`, `FirstBrewed`: `date`, `Description`: `text`, `ImageURL`: `text`, `Abv`: `double precision`, `Ibu`: `double precision`, `TargetFG`: `bigint`, `TargetOg`: `double precision`, `Ebc`: `double precision`, `SRM`: `double precision`, `PH`: `double precision`, `AttenuationLevel`: `double precision`, `Volume`: `jsonb`, `BoilVolume`: `jsonb`, `Method`: `jsonb`, `Ingredients`: `jsonb`, `FoodPairing`: `ARRAYtext`, `BrewersTips`: `text`, `ContributedBy`: `text`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_           = bytes.MinRead
)

func testBeersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(beerPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(beerAllColumns) == len(beerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Beers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, beerDBTypes, true, beerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBeersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(beerAllColumns) == len(beerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Beer{}
	if err = randomize.Struct(seed, o, beerDBTypes, true, beerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Beers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, beerDBTypes, true, beerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(beerAllColumns, beerPrimaryKeyColumns) {
		fields = beerAllColumns
	} else {
		fields = strmangle.SetComplement(
			beerAllColumns,
			beerPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BeerSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBeersUpsert(t *testing.T) {
	t.Parallel()

	if len(beerAllColumns) == len(beerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Beer{}
	if err = randomize.Struct(seed, &o, beerDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Beer: %s", err)
	}

	count, err := Beers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, beerDBTypes, false, beerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Beer struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Beer: %s", err)
	}

	count, err = Beers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
